apiVersion: component.kyma-project.io/v1alpha1
kind: Manifest
metadata:
  labels:
    operator.kyma-project.io/channel: stable
    operator.kyma-project.io/controller-name: manifest
    operator.kyma-project.io/kyma-name: kyma-sample
  name: manifestkyma-sample1
  namespace: default
spec:
  defaultConfig:
    ref: sha256:9d37fb366e4371b44c94496f3db276bd6f3a1019c9d44077b689c68ec6486c1e
    name: kyma-project.io/module/example
    repo: k3d-registry.localhost:52445/signed/component-descriptors
    type: oci-ref
  installs:
  - source:
      name: nginx-ingress
      repo: k3d-registry.localhost:52445/signed/component-descriptors
      ref: sha256:600989483c323dac3ddec5c636c76e23714bedac3192cb1d7ee4b99c06db708b
      type: oci-ref
    name: nginx-ingress
    overrideSelector:
      matchLabels:
        extension.kyma-project.io/config-override: override-me
  - source:
      chartName: nginx-stable/nginx-ingress
      url: https://helm.nginx.com/stable
      type: helm-chart
      version: 1
    name: nginx-stable
    overrideSelector:
      matchLabels:
        extension.kyma-project.io/config-override: override-me
  sync:
    enabled: false
